services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${API_CONTAINER_NAME}
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${API_GEOQUIBIDY_PORT}:${API_PORT}"
    volumes:
      - .:/app
    command: uvicorn src.main:app --host ${API_HOST} --port ${API_PORT} --reload

  db:
    image: postgis/postgis:16-3.4
    container_name: ${POSTGRES_CONTAINER_NAME}
    env_file:
      - .env
    ports:
      - "${POSTGRES_GEOQUBIDY_PORT}:${POSTGRES_PORT}"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  db_data:
